### ISSUE TITLE
This repo can auto-publish to `galaxy.ansible.com` 

### ISSUE THREAD

**Issue by sgnn7** [cyberark/ansible-conjur-collection#19]
Currently publishing is manual but it could be automated relatively easy.

AC:
- [x] When a release (or tag) is made, [our collection](https://galaxy.ansible.com/cyberark/conjur) is updated with the new version

**Comment by izgeri** [comment]
Note: the API key is being added to conjurops, see conjurinc/ops#645. The key / path in conjurops (and ensuring the connected user has write access to the galaxy collection) is needed before this task can be completed.

**Comment by gundalow** [comment]
We (Ansible Team) might be able to do this with Zuul-CI, which will publish when you push a git tag to Galaxy.
Just need to check about process & policy for repos outside of github.com/ansible-collections

If you don't hear from me within the week please ping me on this ticket

**Comment by izgeri** [comment]
cool @gundalow! thanks for connecting with us

in case that doesn't work out, we have creds now for a bot user who could publish this in galaxy as part of our jenkins pipeline using the creds defined at `ansible/galaxy/username` and `ansible/galaxy/api-key` in our dev conjur cluster

**Comment by izgeri** [comment]
Ansible docs on publishing collections: https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#publishing-collections

**Comment by BradleyBoutcher** [comment]
Feature added: https://github.com/cyberark/ansible-conjur-collection/commit/f956691858078ae1b7d44c145df0e6d6a3165e4c
