### ISSUE TITLE
There is a new release of the Conjur collection

### ISSUE THREAD

**Issue by izgeri** [cyberark/ansible-conjur-collection#25]
Depends on #23 
Depends on #19 

In the next week or so we'd like to add the ability to auto-publish our collection to Ansible Galaxy (#19). We also had a recent contribution (#23) that enables this project to be used with [Conjur authn-k8s](https://docs.conjur.org/Latest/en/Content/Integrations/kubernetes.htm).

AC:
- [ ] There is a new release of the Conjur Ansible collection, and it's auto-published to Galaxy.

**Comment by BradleyBoutcher** [comment]
Release available
GH: https://github.com/cyberark/ansible-conjur-collection/releases/tag/1.0.6
Ansible-Galaxy: https://galaxy.ansible.com/cyberark/conjur
