### ISSUE TITLE
Inclusion of cyberark.conjur in Ansible 2.10

### ISSUE THREAD

**Issue by felixfontein** [cyberark/ansible-conjur-collection#30]
This collection will be included in Ansible 2.10 because it contains modules and/or plugins that were included in Ansible 2.9. Please review:

* The list of requirements for inclusion in Ansible: https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst
* The roadmap with all important dates for Ansible 2.10: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/COLLECTIONS_2_10.rst

## DEADLINE: 2020-08-18

The latest version of the collection available on August 18 will be included in Ansible 2.10.0, except possibly newer versions which differ only in the patch level. (For details, see [the roadmap](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/COLLECTIONS_2_10.rst)). Please release version 1.0.0 of your collection by this date! **If 1.0.0 does not exist, the same 0.x.y version will be used in all of Ansible 2.10 without updates,** and your 1.x.y release will not be included until Ansible 2.11 (unless you request an exception at a [community working group meeting](https://github.com/ansible/community/issues/539) and go through a demanding manual process to vouch for backwards compatibility . . . you want to avoid this!).

## Follow semantic versioning rules

Your collection versioning must follow all [semver rules](https://semver.org/). This means:

* Patch level releases can only contain bugfixes;
* Minor releases can contain new features, new modules and plugins, and bugfixes, but must not break backwards compatibility;
* Major releases can break backwards compatibility.

## Changelogs and Porting Guide

Your collection should provide data for the Ansible 2.10 changelog and porting guide. The changelog and porting guide are automatically generated from ansible-base, and from the changelogs of the included collections. All changes from the `breaking_changes`, `major_changes`, `removed_features` and `deprecated_features` sections will appear in both the changelog and the porting guide. You have two options for providing changelog fragments to include:

1. If possible, use the [antsibull-changelog tool](https://github.com/ansible-community/antsibull-changelog/), which uses the same changelog fragment as the ansible/ansible repository (see the [documentation](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.rst)).
2. If you cannot use antsibull-changelog, you can provide the changelog in a machine-readable format as `changelogs/changelog.yaml` inside your collection (see the [documentation of changelogs/changelog.yaml format](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelog.yaml-format.md)).

If you cannot contribute to the integrated Ansible changelog using one of these methods, please provide a link to your collection's changelog by creating an issue in https://github.com/ansible-community/ansible-build-data/. If you do not provide `changelogs/changelog.yml` or a link, users will not be able to find out what changed in your collection from the Ansible changelog and porting guide.

## Make sure your collection passes the sanity tests

Run `ansible-test sanity --docker -v` in the collection with the latest [ansible-base](https://pypi.org/project/ansible-base/) or `stable-2.10` ansible/ansible checkout.

## Keep informed

Be sure you're subscribed to:

* [Changes impacting Collections](https://github.com/ansible-collections/overview/issues/45) to track changes that Collection maintainers should be aware of;
* The Bullhorn, a newsletter for the Ansible developer community, [back issues and how to add content](https://github.com/ansible/community/issues/546).

## Questions and Feedback

If you have questions or want to provide feedback, please see [the Feedback section in the collection requirements](https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst#feedback).

(Internal link to keep track of issues: ansible-collections/overview#102)

**Comment by BradleyBoutcher** [comment]
The following work needs to be done to meet requirements listed above:

- [ ] Follow semantic versioning rules
Our versioning does not follow the above description for semantic versioning. Specifically, "Minor releases can contain new features, new modules and plugins, and bugfixes, but must not break backwards compatibility;". Our versions listed in the changelog have been "bug fix" level, but contain more complex changes such as described above.

- [ ] Changelogs and Porting Guide
Our changelog is not natively readable by antsibull-changelog. We may be able to create a `config.yml` that would be readable by this tool. The easiest solution is to create an issue with a link to our changelog, but we should attempt to generate a `changelog.yml` first.

- [ ] Make sure your collection passes the sanity tests
I'm having issues getting `ansible-test sanity` to run in the Dockerfile we use as a testing environment. It seems to be an issue with the python environment there, because I can run it locally. We will need to address any issues generated by this tool

**Comment by izgeri** [comment]
Thanks @BradleyBoutcher! If I understand correctly, we also will need a v1.0.0 release - is that your understanding too? Can you start filing issues for these?

RE: changelogs - we are using a specific changelog format (keepachangelog) in our project to keep it consistent with our other projects, so let's find a way to meet their requirements that doesn't require us to change how we format CHANGELOG.md and doesn't require us duplicating the contents, if possible

I also want to ask what you think about moving the [Conjur Ansible role](https://github.com/cyberark/ansible-conjur-host-identity) into this project before we tag 1.0.0. We could move it and its test suite and not do anything else / any enhancements - wdyt? Is that doable with the above before 8/18?

**Comment by BradleyBoutcher** [comment]
@izgeri 

- Re: 1.0.0 - I do believe we need to tag a 1.0.0 release. This would be based on older commits, correct? Or would we need to retroactively re-version our releases and make 1.0.0 latest? I may need some clarification on how we want to do this.

- Re: changelogs - To clarify my above comment, I was under the impression that we could create a `config.yml` that would allow `ansibull` to read our changelog regardless, but I was mistaken. I think the best route forward is to share a link, otherwise we'll need to maintain two completely different changelogs going forward, which isn't easily done.

- Re: Conjur Ansible Host Identity
I think this is doable for sure, provided we can complete the other tasks in a reasonable amount of time as well.

**Comment by izgeri** [comment]
oh, ha. I didn't see we already had a 1.0 tag. we don't need to retrofit another, no. but we can certainly follow semantic versioning going forward - that is our standard across all projects, and I don't think we need to make any other changes to make that true going forward in this one.

**Comment by izgeri** [comment]
@BradleyBoutcher once you have issues filed for the other items, please reference them here and we'll get that work scheduled.

**Comment by BradleyBoutcher** [comment]
Hi @felixfontein 
We've completed most of these tasks, but have one remaining issue with regards to `ansible-test sanity`.

When performing the `ansible-doc` sanity test for Python 3.7, it attempts to lookup using a path generated from the project directory structure.

```
Run command: ansible-doc -t lookup cyberark.ansible-conjur-collection.conjur_variable
ERROR: Output on stderr from ansible-doc is considered an error.

Command "ansible-doc -t lookup cyberark.ansible-conjur-collection.conjur_variable" returned exit status 0.
>>> Standard Error
[WARNING]: lookup cyberark.ansible-conjur-collection.conjur_variable not found
in: /root/.ansible/plugins/lookup:/usr/share/ansible/plugins/lookup:/root/ansib
le/lib/ansible/plugins/lookup
``` 

Can you help us understand why this lookup fails, and how we can fix this? The documentation for the test is almost completely empty, as [seen here](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ansible-doc.html).

Thank you!

**Comment by felixfontein** [comment]
There's something wrong with your collection name. It should be `conjur`, not `ansible-conjur-collection`. (That's an invalid collection name.)

**Comment by felixfontein** [comment]
How exactly are you running the sanity tests?

**Comment by felixfontein** [comment]
Also, the correct FQCN for the plugin is cyberark.conjur.conjur_variable. This has to be specified to ansible-doc in general. The short form only works because there is a redirect in ansible-base (because the lookup was already in ansible 2.9).

**Comment by BradleyBoutcher** [comment]
Originally, I was running `ansible-test sanity --docker -v` from the project's top level directory, `ansible_collections/cyberark/ansible-conjur-collection`. This is from a clean checkout.

However, if I rename the project directory to `conjur`, and run the same command from the new path (`ansible_collections/cyberark/conjur`), it succeeds like you mentioned. We can't rename the entire repository to `Conjur`, so how can we make sure this meets the requirements for the test? 

Thank you again for helping so quickly!

**Comment by felixfontein** [comment]
How about checking out the repository as `conjur`? There's no need to check it out as `ansible-conjur-collection`, even if it is called that way (`rm -rf /path/to/ansible_collections/cyberark/conjur && git clone git@github.com:cyberark/ansible-conjur-collection.git /path/to/ansible_collections/cyberark/conjur`).

**Comment by BradleyBoutcher** [comment]
We have a work-in-progress Github Action running [here](https://github.com/cyberark/ansible-conjur-collection/runs/976508264?check_suite_focus=true), and I've modified it to checkout the code to `conjur`, rather than the repository name. It looks like that did resolve the `ansible-doc` issue! Thank you so much for helping with this, you saved us a bunch of time.

One final question, is there any output from running the sanity tests we should provide for you?

**Comment by felixfontein** [comment]
Glad to be able to help!

About the sanity test output: I'm not interested in that. (And the community team has no resources to check on all collections.) Just make sure (sanity) tests pass ;)

**Comment by diverdane** [comment]
@felixfontein, do you know if it's possible to add ignore file for sanity tests on the `devel` branch? I know for a specific version of ansible collection, I would create an ignore file with a name that includes the version, e.g. `ignore-2.10.txt`. For the `devel` branch, I had thought the name `ignore-devel.txt` might work, but apparently it doesn't.

Note: I was going to ask this question on the #ansible-community IRC channel, but there might be a meeting in progress based on the channel topic?

**Comment by felixfontein** [comment]
@diverdane the ansible/ansible `devel` branch has version `2.11.0.dev0` or something like that, so you can use `ignore-2.11.txt`. Once the stable-2.11 branch in ansible/ansible has been created, you'd need `ignore-2.12.txt` for devel, and so on.

**Comment by diverdane** [comment]
@felixfontein, thank you once again! Your suggestion worked as advertised!

**Comment by BradleyBoutcher** [comment]
Hey @felixfontein,
Since today is the cut-off, I just wanted to follow up with you. We should meet all the qualifications listed above, but let us know if there's anything else we can do to help!

**Comment by felixfontein** [comment]
@BradleyBoutcher you should also read the full list of qualifications (https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst), not just the summary of the most important points in this issue.

Two comments:
1. https://github.com/cyberark/ansible-conjur-collection/blob/master/plugins/lookup/conjur_variable.py#L74 needs to use FQCN
2. Some kind of changelog would be nice, that usually helps user

**Comment by BradleyBoutcher** [comment]
@felixfontein I can submit a change for the missing FQCN in the example, but we did submit a changelog that was marked as accepted. Is there something else we need to do there?

**Comment by felixfontein** [comment]
@BradleyBoutcher ah right, sorry, I forgot about that one. I just noticed there isn't a changelogs/changelog.yaml file...

**Comment by izgeri** [comment]
@felixfontein I know it's after 8/18 now, and we didn't get the FQCN update in before then. Will we need a new tag to ensure our collection is included in Ansible 2.10? I want to make sure we don't miss out on inclusion, but it's not clear whether a new tag with the changes in it is required or not.

**Comment by felixfontein** [comment]
@izgeri until 2.10.0rc1, new patch versions are still accepted, i.e. docs changes (and other bugfixes) can still get in. So if you release 1.0.7, it will be included in the next beta release.

**Comment by izgeri** [comment]
@BradleyBoutcher can you please prioritize reviewing the full list of requirements [here](https://github.com/ansible-collections/overview/blob/master/collection_requirements.rst) to make sure we meet them, and then cutting a new Ansible tag?

I know this will delay the role migration, but it will make it easier for users to install the collection in the 2.10 betas
