### ISSUE TITLE
Ansible 2.10 Preparation - Changelog Submission

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/ansible-conjur-collection#32]
Per the requirements mentioned in #30, we will need to do as follows:

> If you cannot contribute to the integrated Ansible changelog using one of these methods, please provide a link to your collection's changelog by creating an issue in https://github.com/ansible-community/ansible-build-data/. If you do not provide changelogs/changelog.yml or a link, users will not be able to find out what changed in your collection from the Ansible changelog and porting guide.

Alternatively, we would need to change our changelog format, which would break our organization standard across multiple projects.

**Comment by BradleyBoutcher** [comment]
Submitted: https://github.com/ansible-community/ansible-build-data/issues/28

**Comment by izgeri** [comment]
Thanks @BradleyBoutcher! Since you submitted this, I assigned the card to you and moved it to Review.

**Comment by BradleyBoutcher** [comment]
PR closed - our changelog has been approved!
https://github.com/ansible-community/ansible-build-data/issues/28#issuecomment-672553438
