### ISSUE TITLE
Certificate verification failing for self-signed certificates

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/ansible-conjur-collection#4]
I am receiving the following error when running playbook using this collection:
```
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'cyberark.conjur.conjur_variable'. Error was a <class 'urllib.error.URLError'>, original message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>"}
```

I am using the same certificate certificate returned from the `conjur init` command and I am using the same url and account name also used by `conjur init`.

**Comment by sgnn7** [comment]
I've confirmed this and updated the issue title. 

Using the correct certificate from the server fails to fetch the variables even though the plugin has the correct value to build the SSL context. Without this working, the user _**must**_ use the _**undocumented**_ `validate_certs=False` parameter.
